### ISSUE TITLE
`assistantbot` command does not work

### ISSUE THREAD

**Issue by yevhenmazur** [cs100675jvv/project-f16df35s#16]
### How to reproduce:
Follow the steps from Readme for installation.
`assistantbot` command causes an exception.
`❯ assistantbot
Traceback (most recent call last):
  File ".../project-f16df35s/.venv/bin/assistantbot", line 5, in <module>
    from main import main
ModuleNotFoundError: No module named 'main'`

**Comment by webness** [comment]
Fixed here:
https://github.com/cs100675jvv/project-f16df35s/pull/30
